### ISSUE TITLE
Stylesheet not loading

### ISSUE THREAD

**Issue by sanudatta11** [theSage21/judge-interface#1]
I did everything as mentioned and also cross checked each installation. Nginx is working fine and so is all others, but the stylesheet is not showing.

**Comment by theSage21** [comment]
The judge interfaces have been deprecated and merged into the [openjudge](https://github.com/theSage21/openjudge) project. Please open an issue there.

In the mean time, also find out what is the error code being returned by the server. Does the static content get served when you use the `./manage.py runserver` command?
